import json
import shutil
import tempfile
import types
import unittest
from pathlib import Path


class _Fake:
    def __init__(self, *args, **kwargs):
        self._text = str(args[0]) if args else ""
        self._checked = False
        self._enabled = True
        self._visible = True
        self._children = []

    def __call__(self, *args, **kwargs):
        return _Fake()

    def __getattr__(self, name):
        if name in ("textChanged", "clicked", "timeout", "enabled_changed", "currentTextChanged"):
            return _FakeSignal()
        return _Fake()

    def __or__(self, other):
        return self

    def addWidget(self, widget, *args, **kwargs):
        self._children.append(widget)

    def addLayout(self, layout, *args, **kwargs):
        self._children.append(layout)

    def addStretch(self, *args, **kwargs):
        pass

    def setText(self, text):
        self._text = str(text)

    def text(self):
        return self._text

    def setPlaceholderText(self, *args, **kwargs):
        pass

    def setChecked(self, checked):
        self._checked = bool(checked)

    def isChecked(self):
        return self._checked

    def setEnabled(self, enabled):
        self._enabled = bool(enabled)

    def isEnabled(self):
        return self._enabled

    def setVisible(self, visible):
        self._visible = bool(visible)

    def isVisible(self):
        return self._visible

    def hide(self):
        self._visible = False

    def show(self):
        self._visible = True

    def deleteLater(self):
        pass


class _FakeSignal:
    def connect(self, *args, **kwargs):
        pass

    def emit(self, *args, **kwargs):
        pass


def _install_fake_pyqt():
    import sys

    if "PyQt6" in sys.modules:
        return
    pyqt = types.ModuleType("PyQt6")
    qtcore = types.ModuleType("PyQt6.QtCore")
    qtgui = types.ModuleType("PyQt6.QtGui")
    qtwidgets = types.ModuleType("PyQt6.QtWidgets")

    qtcore.Qt = _Fake()
    qtcore.QThread = _Fake
    qtcore.pyqtSignal = lambda *args, **kwargs: _FakeSignal()
    for name in ("QTimer", "QSize", "QMimeData", "QPoint", "QRect", "QEvent"):
        setattr(qtcore, name, _Fake)
    for name in (
        "QColor", "QFont", "QPalette", "QPainter", "QLinearGradient",
        "QPainterPath", "QPen", "QDragEnterEvent", "QDropEvent",
        "QDragLeaveEvent", "QMouseEvent", "QTextCursor",
    ):
        setattr(qtgui, name, _Fake)
    for name in (
        "QApplication", "QMainWindow", "QWidget", "QVBoxLayout", "QHBoxLayout",
        "QLabel", "QPushButton", "QComboBox", "QLineEdit", "QTextEdit",
        "QScrollArea", "QFrame", "QFileDialog", "QSizePolicy", "QSpacerItem",
        "QCheckBox", "QGridLayout", "QGraphicsDropShadowEffect",
    ):
        setattr(qtwidgets, name, _Fake)

    sys.modules["PyQt6"] = pyqt
    sys.modules["PyQt6.QtCore"] = qtcore
    sys.modules["PyQt6.QtGui"] = qtgui
    sys.modules["PyQt6.QtWidgets"] = qtwidgets


_install_fake_pyqt()

import app


def _form(**overrides):
    data = {
        "title_base": "Prelude",
        "artist": "Artist",
        "bpm": "180",
        "bpm_base": "180.0",
        "set": "single",
        "purchase": "",
        "side": "0",
        "bg": "base_light",
        "version": "1.0",
        "chart_designer": "Chart",
        "jacket_designer": "Jacket",
        "rating": "9",
        "rating_plus": False,
        "pack_id": "prelude_pack",
        "pack_name": "Prelude Pack",
        "pack_description": "Practice clips generated by Arc Slicer.",
        "pack_section": "collab",
        "pack_img": "select_prelude_pack.png",
        "pack_cover_source": "auto",
        "pack_cover_path": "",
    }
    data.update(overrides)
    return data


def _read_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


class _PackExportCase(unittest.TestCase):
    def setUp(self):
        self.old_out_dir = app.OUT_DIR
        self.old_get_ffmpeg = app._get_ffmpeg
        self.old_slice_ogg = app.slice_ogg
        self.old_slice_aff = app.slice_aff
        self.old_render_pack_cover = app.render_pack_cover
        self.td = tempfile.TemporaryDirectory()
        self.root = Path(self.td.name)
        app.OUT_DIR = self.root / "out"
        app._get_ffmpeg = lambda: "ffmpeg"
        self.cover_sources = []
        self.slice_ogg_calls = []
        self.slice_aff_calls = []
        self.logs = []

        def fake_slice_ogg(_in_path, out_path, start, end, speed):
            self.slice_ogg_calls.append((start, end, speed, Path(out_path).parent.name))
            Path(out_path).write_bytes(f"ogg-{start}-{end}-{speed}".encode())

        def fake_slice_aff(_text, _start, _end, speed, warnings=None):
            self.slice_aff_calls.append((_start, _end, speed))
            return f"AudioOffset:0\n-\ntiming(0,{100 * speed:.2f},4.00);\n"

        def fake_cover_renderer(src, dest, log_fn=None):
            self.cover_sources.append(Path(src).name)
            Path(dest).parent.mkdir(parents=True, exist_ok=True)
            Path(dest).write_bytes(b"PNG374x750:" + Path(src).read_bytes())

        app.slice_ogg = fake_slice_ogg
        app.slice_aff = fake_slice_aff
        app.render_pack_cover = fake_cover_renderer
        self.songs_dir = self.root / "songs"
        song = self.songs_dir / "prelude_heavensdoor"
        song.mkdir(parents=True)
        (song / "base.ogg").write_bytes(b"audio")
        (song / "2.aff").write_text("AudioOffset:0\n-\ntiming(0,100.00,4.00);\n", encoding="utf-8")
        self.song_dir = song

    def tearDown(self):
        app.OUT_DIR = self.old_out_dir
        app._get_ffmpeg = self.old_get_ffmpeg
        app.slice_ogg = self.old_slice_ogg
        app.slice_aff = self.old_slice_aff
        app.render_pack_cover = self.old_render_pack_cover
        self.td.cleanup()

    def log(self, text, kind="normal"):
        self.logs.append((text, kind))

    def do_slice(self, *, form=None, songlist=True, packlist=True, current=True, library=False):
        return app.do_slice(
            self.songs_dir,
            "prelude_heavensdoor",
            [{"s": 21000, "e": 22000}],
            1.0,
            self.log,
            form or _form(),
            songlist_enabled=songlist,
            current_export_enabled=current,
            library_export_enabled=library,
            packlist_enabled=packlist,
            duration_getter=lambda _path: 120_000,
        )


class V21PackTemplateTests(unittest.TestCase):
    def test_default_pack_form_uses_source_id(self):
        data = app.default_pack_form_for_song("source_song")
        self.assertEqual(data["pack_id"], "source_song")
        self.assertEqual(data["pack_name"], "source_song")
        self.assertEqual(data["pack_description"], "")
        self.assertEqual(data["pack_section"], "collab")
        self.assertEqual(data["pack_img"], "select_source_song.png")

    def test_pack_template_rejects_invalid_id_and_img(self):
        for overrides in (
            {"pack_id": "bad id"},
            {"pack_id": "中文"},
            {"pack_img": "../x.png"},
            {"pack_img": "C:\\x.png"},
            {"pack_img": "x.jpg"},
        ):
            with self.subTest(overrides=overrides):
                with self.assertRaises(ValueError):
                    app.pack_template_from_form(_form(**overrides), "source")

    def test_upload_cover_requires_existing_png_jpg_or_jpeg(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            png = root / "cover.png"
            jpg = root / "cover.jpg"
            jpeg = root / "cover.jpeg"
            for path in (png, jpg, jpeg):
                path.write_bytes(b"image")
                template = app.pack_template_from_form(
                    _form(pack_cover_source="upload", pack_cover_path=str(path)),
                    "source",
                )
                self.assertEqual(template.cover_path, str(path))
            with self.assertRaises(ValueError):
                app.pack_template_from_form(_form(pack_cover_source="upload", pack_cover_path=str(root / "x.gif")), "source")

    def test_packlist_entry_shape_has_no_unconfirmed_fields(self):
        template = app.pack_template_from_form(_form(), "source")
        entry = app.build_packlist_entry(template)
        self.assertEqual(set(entry), {"id", "section", "plus_character", "name_localized", "description_localized", "img"})
        self.assertEqual(entry["section"], "collab")
        self.assertEqual(entry["plus_character"], -1)

    def test_pack_section_from_form_is_exported_and_unknown_values_fallback(self):
        template = app.pack_template_from_form(_form(pack_section="archive"), "source")
        self.assertEqual(template.section, "archive")
        self.assertEqual(app.build_packlist_entry(template)["section"], "archive")

        for value in (None, "", "unknown_value"):
            with self.subTest(value=value):
                data = _form()
                if value is None:
                    data.pop("pack_section")
                else:
                    data["pack_section"] = value
                template = app.pack_template_from_form(data, "source")
                self.assertEqual(template.section, "collab")

    def test_empty_pack_description_stays_empty_in_template_and_packlist(self):
        template = app.pack_template_from_form(_form(pack_description=""), "source")
        entry = app.build_packlist_entry(template)
        self.assertEqual(template.description, "")
        self.assertEqual(entry["description_localized"]["en"], "")

    def test_cover_crop_geometry_center_crop(self):
        self.assertEqual(app._cover_crop_geometry(1000, 1000), (750, 750, 188, 0))
        self.assertEqual(app._cover_crop_geometry(100, 1000), (374, 3740, 0, 1495))


class V21PackDoSliceTests(_PackExportCase):
    def test_songlist_disabled_packlist_checked_writes_no_pack_resources(self):
        (self.song_dir / "1080_base.jpg").write_bytes(b"jacket")
        code = self.do_slice(songlist=False, packlist=True)

        self.assertEqual(code, 0, self.logs)
        songs = app.current_export_songs_dir(app.OUT_DIR)
        self.assertFalse((songs / "songlist").exists())
        self.assertFalse((songs / "packlist").exists())
        self.assertFalse((songs / "pack").exists())

    def test_packlist_enabled_writes_current_pack_resources_and_sets_songlist_set(self):
        (self.song_dir / "1080_base.jpg").write_bytes(b"jacket")
        code = self.do_slice()

        self.assertEqual(code, 0, self.logs)
        songs = app.current_export_songs_dir(app.OUT_DIR)
        song = _read_json(songs / "songlist")["songs"][0]
        pack = _read_json(songs / "packlist")["packs"][0]
        self.assertEqual(song["set"], "prelude_pack")
        self.assertEqual([d["ratingClass"] for d in song["difficulties"]], [0, 1, 2])
        self.assertEqual(pack["id"], "prelude_pack")
        self.assertEqual(pack["img"], "select_prelude_pack.png")
        self.assertEqual(pack["section"], "collab")
        self.assertEqual(pack["plus_character"], -1)
        self.assertTrue((songs / "pack" / "select_prelude_pack.png").is_file())
        self.assertEqual(self.cover_sources, ["1080_base.jpg"])

    def test_empty_pack_description_exports_empty_localized_description(self):
        (self.song_dir / "1080_base.jpg").write_bytes(b"jacket")
        code = self.do_slice(form=_form(pack_description=""))

        self.assertEqual(code, 0, self.logs)
        songs = app.current_export_songs_dir(app.OUT_DIR)
        pack = _read_json(songs / "packlist")["packs"][0]
        self.assertEqual(pack["description_localized"]["en"], "")

    def test_explicit_pack_description_is_preserved_in_export(self):
        (self.song_dir / "1080_base.jpg").write_bytes(b"jacket")
        code = self.do_slice(form=_form(pack_description="风暴尾杀专项训练"))

        self.assertEqual(code, 0, self.logs)
        songs = app.current_export_songs_dir(app.OUT_DIR)
        pack = _read_json(songs / "packlist")["packs"][0]
        self.assertEqual(pack["description_localized"]["en"], "风暴尾杀专项训练")

    def test_pack_section_is_preserved_in_export(self):
        (self.song_dir / "1080_base.jpg").write_bytes(b"jacket")
        code = self.do_slice(form=_form(pack_section="archive"))

        self.assertEqual(code, 0, self.logs)
        songs = app.current_export_songs_dir(app.OUT_DIR)
        pack = _read_json(songs / "packlist")["packs"][0]
        self.assertEqual(pack["section"], "archive")

    def test_packlist_export_uses_pack_id_as_songlist_set_even_if_set_differs(self):
        (self.song_dir / "1080_base.jpg").write_bytes(b"jacket")
        code = self.do_slice(form=_form(set="base", pack_id="tempestissimo", pack_img="select_tempestissimo.png"))

        self.assertEqual(code, 0, self.logs)
        songs = app.current_export_songs_dir(app.OUT_DIR)
        song = _read_json(songs / "songlist")["songs"][0]
        pack = _read_json(songs / "packlist")["packs"][0]
        self.assertEqual(song["set"], "tempestissimo")
        self.assertEqual(pack["id"], "tempestissimo")
        self.assertTrue((songs / "pack" / "select_tempestissimo.png").is_file())

    def test_title_base_and_pack_name_do_not_change_segment_id_or_directory(self):
        (self.song_dir / "1080_base.jpg").write_bytes(b"jacket")
        form = _form(
            title_base="Display Practice",
            pack_id="practice_pack",
            pack_name="Visible Pack Name",
            pack_img="select_practice_pack.png",
        )
        code = self.do_slice(form=form)

        self.assertEqual(code, 0, self.logs)
        songs = app.current_export_songs_dir(app.OUT_DIR)
        segment_id = "prelude_heavensdoor_21000_22000_x1"
        song = _read_json(songs / "songlist")["songs"][0]
        pack = _read_json(songs / "packlist")["packs"][0]
        self.assertTrue((songs / segment_id).is_dir())
        self.assertEqual(song["id"], segment_id)
        self.assertIn("Display Practice", song["title_localized"]["en"])
        self.assertEqual(pack["name_localized"]["en"], "Visible Pack Name")

    def test_packlist_disabled_preserves_songlist_set(self):
        (self.song_dir / "1080_base.jpg").write_bytes(b"jacket")
        code = self.do_slice(packlist=False, form=_form(set="single"))

        self.assertEqual(code, 0, self.logs)
        songs = app.current_export_songs_dir(app.OUT_DIR)
        self.assertEqual(_read_json(songs / "songlist")["songs"][0]["set"], "single")
        self.assertFalse((songs / "packlist").exists())

    def test_each_segment_uses_its_effective_speed_for_outputs_and_songlist(self):
        (self.song_dir / "1080_base.jpg").write_bytes(b"jacket")
        code = app.do_slice(
            self.songs_dir,
            "prelude_heavensdoor",
            [
                {"s": 21000, "e": 23000, "speed_override": 0.5},
                {"s": 21000, "e": 23000, "speed_override": 0.75},
                {"s": 60000, "e": 90000, "speed_override": None},
            ],
            0.9,
            self.log,
            _form(),
            songlist_enabled=True,
            current_export_enabled=True,
            library_export_enabled=False,
            packlist_enabled=True,
            duration_getter=lambda _path: 120_000,
        )

        self.assertEqual(code, 0, self.logs)
        songs = app.current_export_songs_dir(app.OUT_DIR)
        expected_ids = [
            "prelude_heavensdoor_21000_23000_x0p5",
            "prelude_heavensdoor_21000_23000_x0p75",
            "prelude_heavensdoor_60000_90000_x0p9",
        ]
        for segment_id in expected_ids:
            self.assertTrue((songs / segment_id).is_dir(), segment_id)
        doc = _read_json(songs / "songlist")
        self.assertEqual([item["id"] for item in doc["songs"]], expected_ids)
        self.assertIn("0.5×", doc["songs"][0]["title_localized"]["en"])
        self.assertIn("0.75×", doc["songs"][1]["title_localized"]["en"])
        self.assertIn("0.9×", doc["songs"][2]["title_localized"]["en"])
        self.assertEqual([call[2] for call in self.slice_ogg_calls], [0.5, 0.75, 0.9])
        self.assertEqual([call[2] for call in self.slice_aff_calls], [0.5, 0.75, 0.9])

    def test_auto_cover_source_priority_and_fallback(self):
        for present, expected in (
            (("1080_base.jpg", "base.jpg", "1080_base_256.jpg"), "1080_base.jpg"),
            (("base.jpg", "1080_base_256.jpg"), "base.jpg"),
            (("1080_base_256.jpg",), "1080_base_256.jpg"),
        ):
            with self.subTest(present=present):
                shutil.rmtree(app.OUT_DIR, ignore_errors=True)
                self.cover_sources.clear()
                for name in app.JACKET_FILENAMES:
                    path = self.song_dir / name
                    if path.exists():
                        path.unlink()
                for name in present:
                    (self.song_dir / name).write_bytes(name.encode())
                self.assertEqual(self.do_slice(), 0, self.logs)
                self.assertEqual(self.cover_sources, [expected])

    def test_missing_auto_cover_fails_and_preserves_current_export(self):
        current = app.current_export_songs_dir(app.OUT_DIR)
        current.mkdir(parents=True)
        (current / "sentinel.txt").write_text("old", encoding="utf-8")
        code = self.do_slice()

        self.assertEqual(code, 1)
        self.assertEqual((current / "sentinel.txt").read_text(encoding="utf-8"), "old")
        self.assertFalse((current / "packlist").exists())

    def test_upload_cover_writes_png_only_from_uploaded_file(self):
        upload = self.root / "wide.jpg"
        upload.write_bytes(b"uploaded")
        code = self.do_slice(form=_form(pack_cover_source="upload", pack_cover_path=str(upload)))

        self.assertEqual(code, 0, self.logs)
        songs = app.current_export_songs_dir(app.OUT_DIR)
        self.assertTrue((songs / "pack" / "select_prelude_pack.png").is_file())
        self.assertEqual(self.cover_sources, ["wide.jpg"])

    def test_library_failure_does_not_remove_successful_current_export(self):
        (self.song_dir / "1080_base.jpg").write_bytes(b"jacket")
        library = app.library_export_songs_dir(app.OUT_DIR)
        library.mkdir(parents=True)
        (library / "packlist").write_text("{bad json", encoding="utf-8")

        code = self.do_slice(current=True, library=True)

        self.assertEqual(code, 1)
        self.assertTrue((app.current_export_songs_dir(app.OUT_DIR) / "packlist").exists())
        self.assertEqual((library / "packlist").read_text(encoding="utf-8"), "{bad json")


def _write_stage(stage: Path, song_id: str, pack_id: str, img: str, img_bytes: bytes):
    songs = stage / "songs"
    song_dir = songs / song_id
    pack_dir = songs / "pack"
    song_dir.mkdir(parents=True)
    pack_dir.mkdir(parents=True)
    (song_dir / "2.aff").write_text("-\n", encoding="utf-8")
    (songs / "songlist").write_text(json.dumps({"songs": [{"id": song_id, "set": pack_id}]}), encoding="utf-8")
    (songs / "packlist").write_text(json.dumps({"packs": [app.build_packlist_entry(app.PackTemplate(
        pack_id=pack_id,
        name=pack_id,
        description="desc",
        img=img,
        cover_source="auto",
    ))]}), encoding="utf-8")
    (pack_dir / img).write_bytes(img_bytes)


class V21PackLibraryMergeTests(unittest.TestCase):
    def setUp(self):
        self.td = tempfile.TemporaryDirectory()
        self.root = Path(self.td.name)
        self.out = self.root / "out"

    def tearDown(self):
        self.td.cleanup()

    def test_new_pack_is_appended_and_unrelated_resources_are_preserved(self):
        songs = app.library_export_songs_dir(self.out)
        (songs / "pack").mkdir(parents=True)
        (songs / "unlock").write_text("unlock", encoding="utf-8")
        (songs / "pack" / "old.png").write_bytes(b"old")
        (songs / "packlist").write_text(json.dumps({"packs": [{"id": "old", "img": "old.png"}]}), encoding="utf-8")
        stage = self.root / "stage"
        _write_stage(stage, "song_new", "new", "new.png", b"new")

        app.merge_staging_into_library_export(stage, self.out)

        packs = _read_json(songs / "packlist")["packs"]
        self.assertEqual([p["id"] for p in packs], ["old", "new"])
        self.assertEqual((songs / "pack" / "old.png").read_bytes(), b"old")
        self.assertEqual((songs / "pack" / "new.png").read_bytes(), b"new")
        self.assertEqual((songs / "unlock").read_text(encoding="utf-8"), "unlock")

    def test_same_pack_id_replaces_in_place_and_can_overwrite_cover(self):
        songs = app.library_export_songs_dir(self.out)
        (songs / "pack").mkdir(parents=True)
        (songs / "pack" / "same.png").write_bytes(b"old")
        (songs / "packlist").write_text(json.dumps({"packs": [
            {"id": "a", "img": "a.png"},
            {"id": "same", "img": "same.png", "name_localized": {"en": "old"}},
        ]}), encoding="utf-8")
        stage = self.root / "stage"
        _write_stage(stage, "song_same", "same", "same.png", b"new")

        app.merge_staging_into_library_export(stage, self.out)

        packs = _read_json(songs / "packlist")["packs"]
        self.assertEqual([p["id"] for p in packs], ["a", "same"])
        self.assertEqual((songs / "pack" / "same.png").read_bytes(), b"new")

    def test_same_img_different_pack_identical_content_is_allowed(self):
        songs = app.library_export_songs_dir(self.out)
        (songs / "pack").mkdir(parents=True)
        (songs / "pack" / "shared.png").write_bytes(b"same")
        (songs / "packlist").write_text(json.dumps({"packs": [{"id": "old", "img": "shared.png"}]}), encoding="utf-8")
        stage = self.root / "stage"
        _write_stage(stage, "song_new", "new", "shared.png", b"same")

        app.merge_staging_into_library_export(stage, self.out)

        self.assertEqual([p["id"] for p in _read_json(songs / "packlist")["packs"]], ["old", "new"])

    def test_same_img_different_pack_different_content_is_rejected_and_preserved(self):
        songs = app.library_export_songs_dir(self.out)
        (songs / "pack").mkdir(parents=True)
        (songs / "pack" / "shared.png").write_bytes(b"old")
        (songs / "packlist").write_text(json.dumps({"packs": [{"id": "old", "img": "shared.png"}]}), encoding="utf-8")
        stage = self.root / "stage"
        _write_stage(stage, "song_new", "new", "shared.png", b"new")

        with self.assertRaises(RuntimeError):
            app.merge_staging_into_library_export(stage, self.out)

        self.assertEqual((songs / "pack" / "shared.png").read_bytes(), b"old")
        self.assertEqual([p["id"] for p in _read_json(songs / "packlist")["packs"]], ["old"])

    def test_damaged_library_packlist_fails_without_changes(self):
        songs = app.library_export_songs_dir(self.out)
        songs.mkdir(parents=True)
        (songs / "packlist").write_text("{bad json", encoding="utf-8")
        (songs / "songlist").write_text(json.dumps({"songs": []}), encoding="utf-8")
        stage = self.root / "stage"
        _write_stage(stage, "song_new", "new", "new.png", b"new")

        with self.assertRaises(ValueError):
            app.merge_staging_into_library_export(stage, self.out)

        self.assertEqual((songs / "packlist").read_text(encoding="utf-8"), "{bad json")
        self.assertFalse((songs / "song_new").exists())


class V21PackUiTests(unittest.TestCase):
    class _Check:
        def __init__(self, checked=False):
            self._checked = checked
            self._enabled = True

        def setChecked(self, checked):
            self._checked = bool(checked)

        def isChecked(self):
            return self._checked

        def setEnabled(self, enabled):
            self._enabled = bool(enabled)

        def setVisible(self, visible):
            self._visible = bool(visible)

        def isVisible(self):
            return getattr(self, "_visible", True)

        def setStyleSheet(self, _style):
            pass

        def isEnabled(self):
            return self._enabled

    class _Line:
        def __init__(self, text=""):
            self._text = text
            self._enabled = True

        def setText(self, text):
            self._text = str(text)

        def text(self):
            return self._text

        def setEnabled(self, enabled):
            self._enabled = bool(enabled)

        def setVisible(self, visible):
            self._visible = bool(visible)

        def isVisible(self):
            return getattr(self, "_visible", True)

        def setStyleSheet(self, _style):
            pass

    class _Combo:
        def __init__(self, values=()):
            self._values = list(values)
            self._value = self._values[0] if self._values else ""
            self._enabled = True
            self._editable = False
            self.currentTextChanged = _FakeSignal()

        def addItems(self, values):
            self._values.extend(values)
            if not self._value and self._values:
                self._value = self._values[0]

        def setEditable(self, editable):
            self._editable = bool(editable)

        def isEditable(self):
            return self._editable

        def currentText(self):
            return self._value

        def findText(self, value):
            try:
                return self._values.index(value)
            except ValueError:
                return -1

        def setCurrentIndex(self, index):
            self._value = self._values[index]

        def setCurrentText(self, value):
            if value in self._values:
                self._value = value

        def setEnabled(self, enabled):
            self._enabled = bool(enabled)

    def _panel(self):
        panel = app.SonglistPanel.__new__(app.SonglistPanel)
        panel._enabled = self._Check(False)
        panel._packlist_enabled = self._Check(False)
        panel.metadata_changed = _FakeSignal()
        panel.enabled_changed = _FakeSignal()
        panel._pack_inputs = {
            "pack_id": self._Line(),
            "pack_name": self._Line(),
            "pack_description": self._Line(),
            "pack_img": self._Line(),
        }
        panel._pack_section = self._Combo(app.PACK_SECTION_OPTIONS)
        panel._pack_upload_check = self._Check(False)
        panel._pack_cover_path = self._Line()
        panel._pack_controls = [
            *panel._pack_inputs.values(),
            panel._pack_section,
            panel._pack_upload_check,
            panel._pack_cover_path,
        ]
        panel._last_pack_default_source = ""
        panel._syncing_shared_pack_id = False
        panel._resetting_source = False
        panel._last_shared_pack_id = ""
        panel._expanded = False
        panel._pack_expanded = False
        panel._body = self._Line()
        panel._pack_body = self._Line()
        panel._packlist_item = self._Line()
        panel._songlist_hint = self._Line()
        panel._packlist_hint = self._Line()
        panel._toggle_btn = self._Line()
        panel._pack_toggle_btn = self._Line()
        panel._inputs = {key: self._Line() for _label, key, _placeholder in app.SonglistPanel._FIELDS}
        panel._rating_plus = self._Check(False)
        panel._refresh_packlist_state()
        return panel

    def test_songlist_panel_pack_defaults_and_dependency(self):
        panel = self._panel()
        panel.update_pack_defaults("song_a")
        self.assertEqual(panel.get_form_data()["pack_id"], "song_a")
        self.assertEqual(panel.get_form_data()["pack_img"], "select_song_a.png")
        self.assertEqual(panel.get_form_data()["pack_section"], "collab")
        self.assertFalse(panel.is_packlist_enabled())
        self.assertFalse(panel._packlist_enabled.isEnabled())

        panel.set_packlist_enabled(True)
        self.assertFalse(panel._packlist_enabled.isEnabled())
        panel.set_songlist_enabled(True)
        self.assertTrue(panel._packlist_enabled.isEnabled())
        self.assertTrue(panel.is_packlist_enabled())

    def test_pack_defaults_do_not_override_manual_edits(self):
        panel = self._panel()
        panel.update_pack_defaults("song_a")
        panel._pack_inputs["pack_id"].setText("manual")
        panel._pack_inputs["pack_img"].setText("manual.png")
        panel.update_pack_defaults("song_b")
        data = panel.get_form_data()
        self.assertEqual(data["pack_id"], "manual")
        self.assertEqual(data["pack_img"], "manual.png")

    def test_shared_pack_id_inputs_mirror_each_other_and_update_default_img(self):
        panel = self._panel()
        panel.reset_for_source("song_a")

        panel._inputs["set"].setText("practice_pack")
        panel._on_set_pack_id_changed("practice_pack")
        data = panel.get_form_data()
        self.assertEqual(data["set"], "practice_pack")
        self.assertEqual(data["pack_id"], "practice_pack")
        self.assertEqual(data["pack_img"], "select_practice_pack.png")

        panel._pack_inputs["pack_img"].setText("custom.png")
        panel._pack_inputs["pack_id"].setText("manual_pack")
        panel._on_pack_id_changed("manual_pack")
        data = panel.get_form_data()
        self.assertEqual(data["set"], "manual_pack")
        self.assertEqual(data["pack_id"], "manual_pack")
        self.assertEqual(data["pack_img"], "custom.png")

    def test_reset_for_new_source_clears_old_metadata_and_segments_defaults(self):
        panel = self._panel()
        panel._inputs["title_base"].setText("Old Title")
        panel._inputs["artist"].setText("Old Artist")
        panel._inputs["bpm"].setText("240")
        panel._inputs["bpm_base"].setText("240")
        panel._inputs["chart_designer"].setText("Old Chart")
        panel._inputs["jacket_designer"].setText("Old Jacket")
        panel._inputs["rating"].setText("10")
        panel._rating_plus.setChecked(True)
        panel._pack_inputs["pack_id"].setText("old_pack")
        panel._pack_inputs["pack_name"].setText("Old Pack")
        panel._pack_inputs["pack_description"].setText("Old Description")
        panel._pack_inputs["pack_img"].setText("old.png")
        panel._set_pack_section("archive")
        panel._pack_upload_check.setChecked(True)
        panel._pack_cover_path.setText("old-cover.png")

        panel.reset_for_source("tempestissimo")
        data = panel.get_form_data()

        self.assertEqual(data["title_base"], "tempestissimo")
        self.assertEqual(data["set"], "tempestissimo")
        self.assertEqual(data["pack_id"], "tempestissimo")
        self.assertEqual(data["pack_name"], "tempestissimo")
        self.assertEqual(data["pack_img"], "select_tempestissimo.png")
        self.assertEqual(data["pack_section"], "collab")
        self.assertEqual(data["artist"], "")
        self.assertEqual(data["bpm"], "")
        self.assertEqual(data["bpm_base"], "")
        self.assertEqual(data["chart_designer"], "")
        self.assertEqual(data["jacket_designer"], "")
        self.assertEqual(data["rating"], "")
        self.assertEqual(data["pack_description"], "")
        self.assertFalse(data["rating_plus"])
        self.assertEqual(data["pack_cover_source"], "auto")
        self.assertEqual(data["pack_cover_path"], "")


if __name__ == "__main__":
    unittest.main()
