"""Metadata and songlist panel widgets."""
from __future__ import annotations

from pathlib import Path

from PyQt6.QtCore import Qt, pyqtSignal, QMimeData
from PyQt6.QtGui import QDragEnterEvent, QDropEvent, QDragLeaveEvent, QFont
from PyQt6.QtWidgets import (
    QCheckBox, QComboBox, QFileDialog, QFrame, QGridLayout, QHBoxLayout,
    QLabel, QLineEdit, QPushButton, QVBoxLayout, QWidget,
)

from arc_slicer.theme import C_ACCENT, C_BORDER, C_BORDER2, C_CARD, C_CARD2, C_LABEL, C_MUTED, C_TEXT, C_TEXT2

PACK_DEFAULT_SECTION = "collab"
PACK_SECTION_OPTIONS = (
    "collab",
    "arcaea",
    "mainstory",
    "mainstory2",
    "sidestory",
    "archive",
    "free",
)


def _bool_pref(value, default: bool = False) -> bool:
    if value is None:
        value = default
    if isinstance(value, str):
        return value.strip().lower() in ("1", "true", "yes", "on")
    return bool(value)


def default_pack_img_name(pack_id: str) -> str:
    pack_id = str(pack_id or "").strip()
    return f"select_{pack_id}.png"


def normalize_pack_section(value) -> str:
    value = str(value or "").strip()
    if value in PACK_SECTION_OPTIONS:
        return value
    return PACK_DEFAULT_SECTION


def pack_description_placeholder(pack_id: str) -> str:
    pack_id = str(pack_id or "").strip()
    if pack_id:
        return f"{pack_id} practice clips generated by Arc Slicer."
    return "Practice clips generated by Arc Slicer."


def default_pack_form_for_song(source_id: str) -> dict:
    source_id = str(source_id or "").strip()
    return {
        "pack_id": source_id,
        "pack_name": source_id,
        "pack_description": "",
        "pack_section": PACK_DEFAULT_SECTION,
        "pack_img": default_pack_img_name(source_id) if source_id else "",
        "pack_cover_source": "auto",
        "pack_cover_path": "",
    }

def make_label(text: str, size: int = 14, weight: int = 400, color: str = C_TEXT) -> QLabel:
    lbl = QLabel(text)
    f = lbl.font()
    f.setPointSize(size)
    f.setWeight(QFont.Weight(weight))
    lbl.setFont(f)
    lbl.setStyleSheet(f"color: {color}; background: transparent;")
    return lbl


def field_label(text: str) -> QLabel:
    lbl = QLabel(text)
    lbl.setStyleSheet(
        f"font-size: 11px; font-weight: 600; letter-spacing: 1px; "
        f"color: {C_LABEL}; background: transparent;"
    )
    return lbl


def metadata_field_label(text: str) -> QLabel:
    lbl = QLabel(text)
    lbl.setStyleSheet(
        f"font-size: 11px; font-weight: 650; letter-spacing: 0.5px; "
        f"color: {C_MUTED}; background: transparent; border: none; padding: 0;"
    )
    return lbl


def section_title(text: str, subtitle: str = "") -> QLabel:
    full_text = text if not subtitle else f"{text}  {subtitle}"
    lbl = QLabel(full_text)
    lbl.setStyleSheet(
        f"font-size: 13px; font-weight: 750; letter-spacing: 0.2px; "
        f"color: {C_TEXT2}; background: transparent; border: none; padding: 2px 0 4px 0;"
    )
    return lbl


def card_frame(bg: str = C_CARD, border: str = C_BORDER) -> QFrame:
    f = QFrame()
    f.setStyleSheet(
        f"background: {bg}; border: 1px solid {border}; "
        f"border-radius: 12px;"
    )
    return f


class CollapsibleHeader(QFrame):
    clicked = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._hover = False
        self.setCursor(Qt.CursorShape.PointingHandCursor)
        self._refresh_style()

    def _refresh_style(self):
        bg = "#F3F4F6" if self._hover else C_CARD2
        border = C_BORDER if self._hover else C_BORDER2
        self.setStyleSheet(
            f"QFrame {{ background: {bg}; border: 1px solid {border}; border-radius: 9px; }}"
        )

    def enterEvent(self, event: QEvent):
        self._hover = True
        self._refresh_style()
        super().enterEvent(event)

    def leaveEvent(self, event: QEvent):
        self._hover = False
        self._refresh_style()
        super().leaveEvent(event)

    def mouseReleaseEvent(self, event: QMouseEvent):
        if event.button() == Qt.MouseButton.LeftButton:
            self.clicked.emit()
        super().mouseReleaseEvent(event)


class DropZone(QFrame):
    folder_dropped = pyqtSignal(str)
    invalid_dropped = pyqtSignal(str)

    def __init__(self, parent=None):
        super().__init__(parent)
        self._over = False
        self.setAcceptDrops(True)
        self.setCursor(Qt.CursorShape.PointingHandCursor)
        self._setup_ui()
        self._update_style()

    def _setup_ui(self):
        lay = QHBoxLayout(self)
        lay.setContentsMargins(18, 13, 18, 13)
        lay.setSpacing(14)

        icon = QLabel("📂")
        icon.setStyleSheet("font-size: 20px; background: transparent; border: none;")
        icon.setFixedWidth(28)

        text_col = QVBoxLayout()
        text_col.setSpacing(3)
        self._main_lbl = QLabel("将谱面文件夹拖入此处，或点击选择")
        self._main_lbl.setStyleSheet(
            f"font-size: 13px; font-weight: 600; color: {C_MUTED}; background: transparent; border: none;"
        )
        sub_lbl = QLabel("选中的文件夹以快捷方式链接到 songs 目录，无需复制文件")
        sub_lbl.setStyleSheet(
            f"font-size: 11px; color: {C_LABEL}; background: transparent; border: none;"
        )
        text_col.addWidget(self._main_lbl)
        text_col.addWidget(sub_lbl)

        lay.addWidget(icon)
        lay.addLayout(text_col)

    def _update_style(self):
        if self._over:
            self.setStyleSheet(
                f"QFrame {{ background: #EFF6FF; border: 1.5px dashed {C_ACCENT}; border-radius: 12px; }}"
            )
            self._main_lbl.setStyleSheet(
                f"font-size: 13px; font-weight: 600; color: {C_ACCENT}; background: transparent; border: none;"
            )
        else:
            self.setStyleSheet(
                f"QFrame {{ background: {C_CARD2}; border: 1.5px dashed {C_BORDER}; border-radius: 12px; }}"
            )
            self._main_lbl.setStyleSheet(
                f"font-size: 13px; font-weight: 600; color: {C_MUTED}; background: transparent; border: none;"
            )

    def mousePressEvent(self, event: QMouseEvent):
        if event.button() == Qt.MouseButton.LeftButton:
            path = QFileDialog.getExistingDirectory(self, "选择谱面文件夹")
            if path:
                self.folder_dropped.emit(path)

    def dragEnterEvent(self, event: QDragEnterEvent):
        if event.mimeData().hasUrls():
            event.acceptProposedAction()
            self._over = True
            self._update_style()

    def dragLeaveEvent(self, event: QDragLeaveEvent):
        self._over = False
        self._update_style()

    def dropEvent(self, event: QDropEvent):
        self._over = False
        self._update_style()
        for url in event.mimeData().urls():
            path = url.toLocalFile()
            if os.path.isdir(path):
                self.folder_dropped.emit(path)
                break
            if path:
                self.invalid_dropped.emit("请拖入歌曲文件夹，而不是单个文件。")
                break


class SonglistPanel(QFrame):
    """可折叠的 Songlist 元数据配置面板。"""

    enabled_changed = pyqtSignal()
    metadata_changed = pyqtSignal()

    # 字段定义：(显示标签, key, 占位提示)
    _FIELDS = [
        ("曲名基础 TITLE BASE",          "title_base",      "e.g. Fractureray"),
        ("作曲者 ARTIST",                "artist",          "e.g. xi"),
        ("BPM 字符串",                   "bpm",             "e.g. 228"),
        ("基准 BPM (bpm_base)",          "bpm_base",        "e.g. 228.0"),
        ("曲包 ID (set)",                "set",             "e.g. single"),
        ("购买方式 (purchase)",           "purchase",        "留空即可"),
        ("Side  0光/1纷/2消/3Lephon",    "side",            "0"),
        ("背景图 (bg)",                  "bg",              "e.g. base_light"),
        ("游戏版本 (version)",            "version",         "e.g. 5.0"),
        ("谱师 (chartDesigner)",         "chart_designer",  ""),
        ("封面画师 (jacketDesigner)",     "jacket_designer", ""),
        ("定数 RATING",                  "rating",          "9"),
    ]

    def __init__(self, parent=None):
        super().__init__(parent)
        self._expanded = False
        self._pack_expanded = False
        self._songlist_enabled_state = False
        self._packlist_enabled_state = False
        self._packlist_checkbox_enabled_state = False
        self._syncing_shared_pack_id = False
        self._resetting_source = False
        self._last_shared_pack_id = ""
        self.setStyleSheet("QFrame { background: transparent; border: none; }")
        self._setup_ui()

    def _setup_ui(self):
        outer = QVBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0)
        outer.setSpacing(8)

        outer.addWidget(section_title("元数据导出"))

        self._songlist_item = QFrame()
        self._songlist_item.setStyleSheet(
            f"QFrame {{ background: {C_CARD}; border: 1px solid {C_BORDER}; border-radius: 12px; }}"
        )
        songlist_lay = QVBoxLayout(self._songlist_item)
        songlist_lay.setContentsMargins(14, 11, 14, 11)
        songlist_lay.setSpacing(8)
        self._songlist_header = CollapsibleHeader()
        self._songlist_header.clicked.connect(self._toggle)
        songlist_head = QHBoxLayout(self._songlist_header)
        songlist_head.setContentsMargins(10, 7, 10, 7)
        songlist_head.setSpacing(10)
        self._enabled = QCheckBox("生成 songlist")
        self._enabled.setChecked(False)
        self._enabled.setStyleSheet(
            f"color: {C_TEXT2}; font-size: 13px; font-weight: 650; background: transparent; border: none;"
        )
        self._enabled.clicked.connect(self._on_songlist_enabled_changed)
        songlist_head.addWidget(self._enabled)
        songlist_head.addStretch()
        self._toggle_btn = QPushButton("▸")
        self._toggle_btn.clicked.connect(self._toggle)
        songlist_head.addWidget(self._toggle_btn)
        songlist_lay.addWidget(self._songlist_header)
        self._songlist_hint = QLabel("勾选后可填写 songlist 元数据")
        self._songlist_hint.setStyleSheet(
            f"font-size: 12px; color: {C_LABEL}; background: transparent; border: none;"
        )
        songlist_lay.addWidget(self._songlist_hint)
        outer.addWidget(self._songlist_item)

        self._packlist_item = QFrame()
        self._packlist_item.setStyleSheet(
            f"QFrame {{ background: {C_CARD}; border: 1px solid {C_BORDER}; border-radius: 12px; }}"
        )
        pack_item_lay = QVBoxLayout(self._packlist_item)
        pack_item_lay.setContentsMargins(14, 11, 14, 11)
        pack_item_lay.setSpacing(8)
        self._packlist_header = CollapsibleHeader()
        self._packlist_header.clicked.connect(self._toggle_pack)
        pack_head = QHBoxLayout(self._packlist_header)
        pack_head.setContentsMargins(10, 7, 10, 7)
        pack_head.setSpacing(10)
        self._packlist_enabled = QCheckBox("生成 packlist 与曲包资源")
        self._packlist_enabled.setChecked(False)
        self._packlist_enabled.setStyleSheet(
            f"color: {C_TEXT2}; font-size: 13px; font-weight: 650; background: transparent; border: none;"
        )
        self._packlist_enabled.clicked.connect(self._on_packlist_enabled_changed)
        pack_head.addWidget(self._packlist_enabled)
        pack_head.addStretch()
        self._pack_toggle_btn = QPushButton("▸")
        self._pack_toggle_btn.clicked.connect(self._toggle_pack)
        pack_head.addWidget(self._pack_toggle_btn)
        pack_item_lay.addWidget(self._packlist_header)
        self._packlist_hint = QLabel("勾选后可填写曲包信息")
        self._packlist_hint.setStyleSheet(
            f"font-size: 12px; color: {C_LABEL}; background: transparent; border: none;"
        )
        pack_item_lay.addWidget(self._packlist_hint)
        outer.addWidget(self._packlist_item)

        # 面板主体
        self._body = QFrame()
        self._body.setObjectName("songlistBody")
        self._body.setStyleSheet(
            f"QFrame#songlistBody {{ background: {C_CARD}; border: 1px solid {C_BORDER};"
            f" border-radius: 14px; }}"
        )
        self._body.hide()
        songlist_lay.addWidget(self._body)

        body_lay = QVBoxLayout(self._body)
        body_lay.setContentsMargins(22, 18, 22, 18)
        body_lay.setSpacing(14)

        # 说明文字
        note = QLabel(
            "以下信息对所有切片段共用。曲名自动加 01 / 02… 编号，"
            "id 自动取文件夹名，audioPreview/End 自动计算。"
        )
        note.setWordWrap(True)
        note.setStyleSheet(f"font-size: 12px; color: {C_MUTED}; background: transparent; border: none;")
        body_lay.addWidget(note)

        # 字段网格（2 列）
        grid = QGridLayout()
        grid.setHorizontalSpacing(20)
        grid.setVerticalSpacing(12)
        self._inputs: dict[str, QLineEdit] = {}

        for i, (label_text, key, placeholder) in enumerate(self._FIELDS):
            row, col = divmod(i, 2)
            col_lay = QVBoxLayout()
            col_lay.setSpacing(5)
            col_lay.addWidget(metadata_field_label(label_text))
            inp = QLineEdit()
            inp.setPlaceholderText(placeholder)
            if key == "set":
                inp.setText("single")
            elif key == "side":
                inp.setText("0")
            elif key == "rating":
                inp.setText("9")
            col_lay.addWidget(inp)
            grid.addLayout(col_lay, row, col)
            self._inputs[key] = inp
            if key != "set":
                inp.textChanged.connect(self._emit_metadata_changed)

        body_lay.addLayout(grid)

        # Rating Plus 行
        rp_row = QHBoxLayout()
        rp_row.setSpacing(10)
        self._rating_plus = QCheckBox("有 +（ratingPlus）")
        self._rating_plus.setStyleSheet(
            f"color: {C_TEXT2}; font-size: 13px; background: transparent; border: none;"
        )
        rp_row.addWidget(self._rating_plus)
        rp_row.addStretch()
        body_lay.addLayout(rp_row)

        self._pack_body = QFrame()
        self._pack_body.setObjectName("packlistBody")
        self._pack_body.setStyleSheet(
            f"QFrame#packlistBody {{ background: {C_CARD}; border: 1px solid {C_BORDER};"
            f" border-radius: 14px; }}"
        )
        self._pack_body.hide()
        pack_item_lay.addWidget(self._pack_body)
        pack_body_lay = QVBoxLayout(self._pack_body)
        pack_body_lay.setContentsMargins(0, 0, 0, 0)
        pack_body_lay.setSpacing(0)

        pack_frame = QFrame()
        pack_frame.setStyleSheet(
            f"QFrame {{ background: {C_CARD2}; border: 1px solid {C_BORDER2}; border-radius: 12px; }}"
        )
        pack_lay = QVBoxLayout(pack_frame)
        pack_lay.setContentsMargins(14, 12, 14, 12)
        pack_lay.setSpacing(10)
        pack_lay.addWidget(field_label("PACKLIST"))
        self._pack_inputs: dict[str, QLineEdit] = {}
        pack_fields = [
            ("曲包 ID PACK ID", "pack_id", ""),
            ("曲包显示名 PACK NAME", "pack_name", ""),
            ("曲包描述 DESCRIPTION", "pack_description", pack_description_placeholder("")),
            ("曲包封面文件名 IMG", "pack_img", "select_<pack_id>.png"),
        ]
        pack_grid = QGridLayout()
        pack_grid.setHorizontalSpacing(20)
        pack_grid.setVerticalSpacing(10)
        for i, (label_text, key, placeholder) in enumerate(pack_fields):
            row, col = divmod(i, 2)
            col_lay = QVBoxLayout()
            col_lay.setSpacing(5)
            col_lay.addWidget(metadata_field_label(label_text))
            inp = QLineEdit()
            inp.setPlaceholderText(placeholder)
            col_lay.addWidget(inp)
            pack_grid.addLayout(col_lay, row, col)
            self._pack_inputs[key] = inp
            if key != "pack_id":
                inp.textChanged.connect(self._emit_metadata_changed)
        pack_lay.addLayout(pack_grid)

        section_lay = QVBoxLayout()
        section_lay.setSpacing(5)
        section_lay.addWidget(metadata_field_label("曲包分区 SECTION"))
        self._pack_section = QComboBox()
        self._pack_section.addItems(PACK_SECTION_OPTIONS)
        self._pack_section.setEditable(False)
        self._set_pack_section(PACK_DEFAULT_SECTION)
        self._pack_section.currentTextChanged.connect(self._on_pack_section_changed)
        section_lay.addWidget(self._pack_section)
        pack_lay.addLayout(section_lay)

        cover_row = QHBoxLayout()
        cover_row.setSpacing(10)
        self._pack_upload_check = QCheckBox("使用上传图片")
        self._pack_upload_check.setStyleSheet(
            f"color: {C_TEXT2}; font-size: 13px; background: transparent; border: none;"
        )
        self._pack_upload_check.clicked.connect(self._emit_metadata_changed)
        self._pack_cover_path = QLineEdit()
        self._pack_cover_path.setPlaceholderText("PNG / JPG / JPEG")
        self._pack_cover_path.textChanged.connect(self._emit_metadata_changed)
        btn_cover = QPushButton("选择图片")
        btn_cover.setObjectName("btnSec")
        btn_cover.clicked.connect(self._browse_pack_cover)
        cover_row.addWidget(self._pack_upload_check)
        cover_row.addWidget(self._pack_cover_path, 1)
        cover_row.addWidget(btn_cover)
        pack_lay.addLayout(cover_row)
        self._pack_controls = [
            pack_frame,
            *self._pack_inputs.values(),
            self._pack_section,
            self._pack_upload_check,
            self._pack_cover_path,
            btn_cover,
        ]
        self._last_pack_default_source = ""
        self._inputs["set"].textChanged.connect(self._on_set_pack_id_changed)
        self._pack_inputs["pack_id"].textChanged.connect(self._on_pack_id_changed)
        self._update_pack_description_placeholder("")
        pack_body_lay.addWidget(pack_frame)
        self._refresh_packlist_state()

    def _widget_bool(self, widget, fallback: bool, getter_name: str) -> bool:
        getter = getattr(widget, getter_name, None)
        if callable(getter):
            try:
                value = getter()
                if isinstance(value, bool):
                    return value
            except Exception:
                pass
        return bool(fallback)

    def _sync_fake_bool_getter(self, widget, attr_name: str, getter_name: str) -> None:
        getter = getattr(widget, getter_name, None)
        try:
            value = getter() if callable(getter) else None
        except Exception:
            value = None
        if isinstance(value, bool):
            return
        try:
            setattr(widget, getter_name, lambda attr_name=attr_name: bool(getattr(self, attr_name)))
        except Exception:
            pass

    def _set_checked_state(self, widget, attr_name: str, value: bool) -> None:
        setattr(self, attr_name, bool(value))
        try:
            widget.setChecked(bool(value))
        except Exception:
            pass
        self._sync_fake_bool_getter(widget, attr_name, "isChecked")

    def _set_enabled_state(self, widget, attr_name: str, value: bool) -> None:
        setattr(self, attr_name, bool(value))
        try:
            widget.setEnabled(bool(value))
        except Exception:
            pass
        self._sync_fake_bool_getter(widget, attr_name, "isEnabled")

    def _songlist_checked(self) -> bool:
        return self._widget_bool(self._enabled, self._songlist_enabled_state, "isChecked")

    def _packlist_checked(self) -> bool:
        return self._widget_bool(self._packlist_enabled, self._packlist_enabled_state, "isChecked")

    # ── 折叠 / 展开 ───────────────────────────────────────────────────────────

    def _toggle(self):
        if not self._songlist_checked():
            return
        self._expanded = not self._expanded
        self._refresh_packlist_state()

    def _toggle_pack(self):
        if not (self._songlist_checked() and self._packlist_checked()):
            return
        self._pack_expanded = not self._pack_expanded
        self._refresh_packlist_state()

    def _on_songlist_enabled_changed(self):
        if not self._songlist_checked():
            self._expanded = False
            self._pack_expanded = False
        self._refresh_packlist_state()
        self.enabled_changed.emit()

    def _on_packlist_enabled_changed(self):
        if not self._packlist_checked():
            self._pack_expanded = False
        self._refresh_packlist_state()
        self.enabled_changed.emit()
        self._emit_metadata_changed()

    def _emit_metadata_changed(self, *_args):
        if not getattr(self, "_resetting_source", False) and not getattr(self, "_syncing_shared_pack_id", False):
            self.metadata_changed.emit()

    def _sync_shared_pack_id(self, value: str, target: QLineEdit):
        if target.text() == value:
            return
        self._syncing_shared_pack_id = True
        try:
            target.setText(value)
        finally:
            self._syncing_shared_pack_id = False

    def _update_pack_img_for_shared_pack_id(self, old_pack_id: str, new_pack_id: str):
        img_input = self._pack_inputs["pack_img"]
        current_img = img_input.text().strip()
        old_default = default_pack_img_name(old_pack_id) if old_pack_id else ""
        if not current_img or current_img == old_default:
            self._syncing_shared_pack_id = True
            try:
                img_input.setText(default_pack_img_name(new_pack_id) if new_pack_id else "")
            finally:
                self._syncing_shared_pack_id = False

    def _update_pack_description_placeholder(self, pack_id: str | None = None):
        if not hasattr(self, "_pack_inputs") or "pack_description" not in self._pack_inputs:
            return
        target = self._pack_inputs["pack_description"]
        if not hasattr(target, "setPlaceholderText"):
            return
        value = str(pack_id if pack_id is not None else self._pack_inputs["pack_id"].text()).strip()
        target.setPlaceholderText(pack_description_placeholder(value))

    def _pack_section_text(self) -> str:
        section = getattr(self, "_pack_section", None)
        if section is None:
            return PACK_DEFAULT_SECTION
        try:
            text = section.currentText()
            if isinstance(text, str):
                return normalize_pack_section(text)
        except Exception:
            pass
        return normalize_pack_section(getattr(section, "_arc_slicer_value", PACK_DEFAULT_SECTION))

    def _set_pack_section(self, value) -> None:
        normalized = normalize_pack_section(value)
        section = getattr(self, "_pack_section", None)
        if section is None:
            return
        setattr(section, "_arc_slicer_value", normalized)
        try:
            index = section.findText(normalized)
            if isinstance(index, int) and index >= 0:
                section.setCurrentIndex(index)
                return
        except Exception:
            pass
        try:
            section.setCurrentText(normalized)
        except Exception:
            pass

    def _on_pack_section_changed(self, text: str):
        self._set_pack_section(text)
        self._emit_metadata_changed()

    def _on_set_pack_id_changed(self, text: str):
        if self._syncing_shared_pack_id:
            return
        value = str(text).strip()
        old_pack_id = self._last_shared_pack_id
        self._sync_shared_pack_id(value, self._pack_inputs["pack_id"])
        self._update_pack_img_for_shared_pack_id(old_pack_id, value)
        self._last_shared_pack_id = value
        self._update_pack_description_placeholder(value)
        self._emit_metadata_changed()

    def _on_pack_id_changed(self, text: str):
        if self._syncing_shared_pack_id:
            return
        value = str(text).strip()
        old_pack_id = self._last_shared_pack_id
        self._sync_shared_pack_id(value, self._inputs["set"])
        self._update_pack_img_for_shared_pack_id(old_pack_id, value)
        self._last_shared_pack_id = value
        self._update_pack_description_placeholder(value)
        self._emit_metadata_changed()

    def _set_section_button_state(self, button: QPushButton, active: bool, expanded: bool):
        button.setEnabled(bool(active))
        try:
            button._section_button_enabled_state = bool(active)
        except Exception:
            pass
        try:
            button.isEnabled = lambda button=button: bool(getattr(button, "_section_button_enabled_state", False))
        except Exception:
            pass
        button.setText("▾" if expanded and active else "▸")
        color = C_TEXT2 if active else C_LABEL
        button.setStyleSheet(
            f"background: transparent; border: 1px solid transparent; color: {color}; "
            f"font-size: 18px; font-weight: 800; padding: 1px 7px; border-radius: 8px;"
        )

    # ── 读 / 写 ───────────────────────────────────────────────────────────────

    def is_songlist_enabled(self) -> bool:
        return self._songlist_checked()

    def set_songlist_enabled(self, enabled: bool):
        self._set_checked_state(self._enabled, "_songlist_enabled_state", bool(enabled))
        if not enabled:
            self._expanded = False
            self._pack_expanded = False
        self._refresh_packlist_state()

    def is_packlist_enabled(self) -> bool:
        return self._packlist_checked()

    def set_packlist_enabled(self, enabled: bool):
        self._set_checked_state(self._packlist_enabled, "_packlist_enabled_state", bool(enabled))
        if not enabled:
            self._pack_expanded = False
        self._refresh_packlist_state()

    def _refresh_packlist_state(self):
        songlist_enabled = self._songlist_checked()
        packlist_checked = self._packlist_checked()
        packlist_enabled = packlist_checked and songlist_enabled
        self._expanded = bool(self._expanded and songlist_enabled)
        self._pack_expanded = bool(self._pack_expanded and packlist_enabled)
        if hasattr(self, "_body"):
            self._body.setVisible(self._expanded)
        if hasattr(self, "_pack_body"):
            self._pack_body.setVisible(self._pack_expanded)
        if hasattr(self, "_packlist_item"):
            self._packlist_item.setVisible(songlist_enabled)
        if hasattr(self, "_songlist_hint"):
            self._songlist_hint.setVisible(not songlist_enabled)
        if hasattr(self, "_packlist_hint"):
            self._packlist_hint.setVisible(songlist_enabled and not packlist_checked)
        if hasattr(self, "_toggle_btn"):
            self._set_section_button_state(self._toggle_btn, songlist_enabled, self._expanded)
        if hasattr(self, "_pack_toggle_btn"):
            self._set_section_button_state(self._pack_toggle_btn, packlist_enabled, self._pack_expanded)
        self._set_enabled_state(self._packlist_enabled, "_packlist_checkbox_enabled_state", songlist_enabled)
        for widget in getattr(self, "_pack_controls", []):
            widget.setEnabled(packlist_enabled)

    def _browse_pack_cover(self):
        path, _filter = QFileDialog.getOpenFileName(
            self,
            "选择曲包封面图片",
            "",
            "Images (*.png *.jpg *.jpeg)",
        )
        if path:
            self._pack_cover_path.setText(path)
            self._pack_upload_check.setChecked(True)
            self._refresh_packlist_state()
            self._emit_metadata_changed()

    def update_pack_defaults(self, source_id: str):
        source_id = str(source_id or "").strip()
        if not source_id or "目录为空" in source_id:
            return
        old_defaults = default_pack_form_for_song(self._last_pack_default_source)
        new_defaults = default_pack_form_for_song(source_id)
        mapping = {
            "pack_id": "pack_id",
            "pack_name": "pack_name",
            "pack_description": "pack_description",
            "pack_img": "pack_img",
        }
        for key, field in mapping.items():
            inp = self._pack_inputs[field]
            current = inp.text().strip()
            if not current or current == old_defaults.get(key, ""):
                inp.setText(new_defaults[key])
        self._last_pack_default_source = source_id
        self._update_pack_description_placeholder(new_defaults["pack_id"])

    def reset_for_source(self, source_id: str):
        source_id = str(source_id or "").strip()
        if not source_id or "目录为空" in source_id:
            return
        defaults = default_pack_form_for_song(source_id)
        self._resetting_source = True
        try:
            for key in ("artist", "bpm", "bpm_base", "purchase", "bg", "version",
                        "chart_designer", "jacket_designer", "rating"):
                self._inputs[key].setText("")
            self._inputs["side"].setText("0")
            self._inputs["title_base"].setText(source_id)
            self._inputs["set"].setText(defaults["pack_id"])
            self._pack_inputs["pack_id"].setText(defaults["pack_id"])
            self._pack_inputs["pack_name"].setText(defaults["pack_name"])
            self._pack_inputs["pack_description"].setText("")
            self._set_pack_section(PACK_DEFAULT_SECTION)
            self._pack_inputs["pack_img"].setText(defaults["pack_img"])
            self._rating_plus.setChecked(False)
            self._pack_upload_check.setChecked(False)
            self._pack_cover_path.setText("")
            self._last_pack_default_source = source_id
            self._last_shared_pack_id = defaults["pack_id"]
            self._update_pack_description_placeholder(defaults["pack_id"])
        finally:
            self._resetting_source = False
        self._refresh_packlist_state()

    def get_form_data(self) -> dict:
        data = {key: self._inputs[key].text().strip() for _label, key, _placeholder in self._FIELDS}
        set_value = data.get("set", "")
        pack_value = self._pack_inputs["pack_id"].text().strip()
        shared_pack_id = pack_value if pack_value and set_value in ("", "single") else (set_value or pack_value)
        data["set"] = shared_pack_id
        data["rating_plus"] = self._rating_plus.isChecked()
        for key, inp in self._pack_inputs.items():
            data[key] = inp.text().strip()
        data["pack_id"] = shared_pack_id
        pack_id = data.get("pack_id") or ""
        if not data.get("pack_img") and pack_id:
            data["pack_img"] = default_pack_img_name(pack_id)
        data["pack_description"] = data.get("pack_description", "")
        data["pack_section"] = self._pack_section_text()
        data["pack_cover_source"] = "upload" if self._pack_upload_check.isChecked() else "auto"
        data["pack_cover_path"] = self._pack_cover_path.text().strip()
        return data

    def get_meta(self) -> dict | None:
        """返回兼容旧调用的已校验配置字典；V2.1 导出使用 SongTemplate。"""
        if not self._expanded:
            return None
        try:
            return {
                "title_base":      self._inputs["title_base"].text().strip(),
                "artist":          self._inputs["artist"].text().strip(),
                "bpm":             self._inputs["bpm"].text().strip(),
                "bpm_base":        float(self._inputs["bpm_base"].text() or "0"),
                "set":             self._inputs["set"].text().strip() or "single",
                "purchase":        self._inputs["purchase"].text().strip(),
                "side":            int(self._inputs["side"].text() or "0"),
                "bg":              self._inputs["bg"].text().strip(),
                "version":         self._inputs["version"].text().strip(),
                "chart_designer":  self._inputs["chart_designer"].text().strip(),
                "jacket_designer": self._inputs["jacket_designer"].text().strip(),
                "rating":          int(self._inputs["rating"].text() or "9"),
                "rating_plus":     self._rating_plus.isChecked(),
            }
        except ValueError:
            return None

    def set_meta(self, meta: dict):
        """从保存的数据恢复面板内容。"""
        if not meta:
            return
        self._resetting_source = True
        if "songlist_enabled" in meta:
            self.set_songlist_enabled(bool(meta["songlist_enabled"]))
        if "packlist_enabled" in meta:
            self.set_packlist_enabled(_bool_pref(meta.get("packlist_enabled"), False))
        str_keys = ("title_base", "artist", "bpm", "set", "purchase", "bg", "version",
                    "chart_designer", "jacket_designer")
        for k in str_keys:
            if k in meta:
                self._inputs[k].setText(str(meta[k]))
        for k, inp in self._pack_inputs.items():
            if k in meta:
                inp.setText(str(meta[k]))
        self._set_pack_section(meta.get("pack_section", PACK_DEFAULT_SECTION))
        if "pack_cover_source" in meta:
            self._pack_upload_check.setChecked(str(meta.get("pack_cover_source")).lower() == "upload")
        if "pack_cover_path" in meta:
            self._pack_cover_path.setText(str(meta["pack_cover_path"]))
        for k in ("bpm_base", "side", "rating"):
            if k in meta:
                self._inputs[k].setText(str(meta[k]))
        if "rating_plus" in meta:
            self._rating_plus.setChecked(bool(meta["rating_plus"]))
        set_value = self._inputs["set"].text().strip()
        pack_value = self._pack_inputs["pack_id"].text().strip()
        shared_pack_id = pack_value if pack_value and set_value in ("", "single") else (set_value or pack_value)
        self._inputs["set"].setText(shared_pack_id)
        self._pack_inputs["pack_id"].setText(shared_pack_id)
        self._last_shared_pack_id = shared_pack_id
        self._update_pack_description_placeholder(shared_pack_id)
        self._resetting_source = False
        self._refresh_packlist_state()
